# Generated by Django 4.2.23 on 2026-04-26 09:51
#
# Phase 2 PR 2.0 — db_table pinning.
#
# The three licensing models previously had no explicit Meta.db_table, so
# Django named their tables using the default `<app_label>_<model_name>`
# convention: licensing_cachedlicense, licensing_licenseconfigauditlog,
# licensing_licenseconfiguration. Phase 2 will move this app under
# services/identity/ which would change app_label and trigger an automatic
# table rename — so we pin the existing names here.
#
# The new db_table values are byte-identical to the names Django was
# already using, so this migration must perform ZERO database changes.
# We wrap the AlterModelTable ops in SeparateDatabaseAndState with
# state_operations only — guaranteeing the migration touches Django's
# in-memory state but never emits SQL, regardless of Django version.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_seed_service_provider_group'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='cachedlicense',
                    table='licensing_cachedlicense',
                ),
                migrations.AlterModelTable(
                    name='licenseconfigauditlog',
                    table='licensing_licenseconfigauditlog',
                ),
                migrations.AlterModelTable(
                    name='licenseconfiguration',
                    table='licensing_licenseconfiguration',
                ),
            ],
        ),
    ]
