# Generated by Django 5.0.4 on 2026-04-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('outlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateField()),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('location_tag', models.CharField(blank=True, default='', max_length=100)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('is_month_end', models.BooleanField(default=False)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='items.item')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='outlets.outlet')),
            ],
            options={
                'db_table': 'stock_counts',
                'ordering': ['-counted_at'],
            },
        ),
    ]
