# Generated by Django 5.0.4 on 2026-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_approval_sessions_variance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='countsession',
            new_name='count_sessi_outlet__42b2d8_idx',
            old_name='count_sess_outlet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='countsession',
            new_name='count_sessi_status_c87ec2_idx',
            old_name='count_sess_status_idx',
        ),
        migrations.RenameIndex(
            model_name='stockcount',
            new_name='stock_count_outlet__e3e9e9_idx',
            old_name='stock_count_outlet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stockcount',
            new_name='stock_count_approva_be0fda_idx',
            old_name='stock_count_approval_idx',
        ),
        migrations.RenameIndex(
            model_name='stockcount',
            new_name='stock_count_session_729309_idx',
            old_name='stock_count_session_idx',
        ),
        migrations.RenameIndex(
            model_name='variancerecord',
            new_name='variance_re_outlet__9b50b7_idx',
            old_name='variance_outlet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='variancerecord',
            new_name='variance_re_status_f4381f_idx',
            old_name='variance_status_idx',
        ),
        migrations.RenameIndex(
            model_name='variancerecord',
            new_name='variance_re_session_007ad6_idx',
            old_name='variance_session_idx',
        ),
        migrations.AlterField(
            model_name='countsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
