# Generated by Django 5.0.4 on 2026-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
