# Generated by Django 5.0.4 on 2026-04-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_catalog', '0003_item_master_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmasterlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
