# Generated by Django 5.0.4 on 2026-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_catalog', '0005_demand_and_purchasing'),
        ('outlets', '0003_outlet_file_location_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='demandsnapshot',
            name='org_demand_unique_master_outlet',
        ),
        migrations.RenameIndex(
            model_name='demandsnapshot',
            new_name='org_demand__master__4d683b_idx',
            old_name='idx_demand_master_outlet',
        ),
        migrations.RenameIndex(
            model_name='demandsnapshot',
            new_name='org_demand__compute_3552fe_idx',
            old_name='idx_demand_computed_at',
        ),
        migrations.AlterField(
            model_name='demandsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseplanline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='demandsnapshot',
            unique_together={('master_product', 'outlet')},
        ),
    ]
