# Generated by Django 5.0.4 on 2026-04-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_catalog', '0007_stock_age_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockagesnapshot',
            new_name='stock_age_s_outlet__a3f042_idx',
            old_name='stock_age_outlet_item_idx',
        ),
        migrations.RenameIndex(
            model_name='stockagesnapshot',
            new_name='stock_age_s_oldest__62af6a_idx',
            old_name='stock_age_oldest_idx',
        ),
        migrations.RenameIndex(
            model_name='stockagesnapshot',
            new_name='stock_age_s_compute_e8d92d_idx',
            old_name='stock_age_computed_idx',
        ),
        migrations.AlterField(
            model_name='stockagesnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
