# Generated by Django 5.0.4 on 2026-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_possnapshot_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='possnapshot',
            new_name='pos_snapsho_outlet__6a7517_idx',
            old_name='pos_snap_outlet_date_idx',
        ),
        migrations.RenameIndex(
            model_name='possnapshot',
            new_name='pos_snapsho_outlet__eaa870_idx',
            old_name='pos_snap_outlet_date_qty_idx',
        ),
        migrations.RenameIndex(
            model_name='possnapshot',
            new_name='pos_snapsho_item_id_6fe121_idx',
            old_name='pos_snap_item_date_idx',
        ),
    ]
