from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError("Username is required")
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None, **extra_fields):
        extra_fields.setdefault("role", User.Role.ADMIN)
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(username, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    class Role(models.TextChoices):
        STORE_USER = "store_user", "Store User"
        MANAGER = "manager", "Store Manager"
        STAFF = "staff", "Staff"
        ADMIN = "admin", "Admin"
        SERVICE_PROVIDER = "ServiceProvider", "Service Provider"

    username = models.CharField(max_length=150, unique=True)
    role = models.CharField(max_length=30, choices=Role.choices, default=Role.STAFF)
    outlet = models.ForeignKey(
        "outlets.Outlet",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="users",
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    class Meta:
        db_table = "users"

    def __str__(self):
        return f"{self.username} ({self.role})"


class MobileDevice(models.Model):
    """
    One row per mobile-app install. Identified by a UUID generated by the app
    on first launch and sent via the `X-Device-UUID` header on every request.

    Updated on each authenticated mobile API call so admins can audit which
    device submitted which counts / assigned which barcodes, and see per-device
    activity levels.
    """
    device_uuid = models.CharField(max_length=64, unique=True)
    platform = models.CharField(max_length=20, blank=True, default="")
    app_version = models.CharField(max_length=30, blank=True, default="")
    first_seen_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(auto_now=True)
    last_user = models.ForeignKey(
        "accounts.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="mobile_devices",
    )
    last_outlet = models.ForeignKey(
        "outlets.Outlet",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="mobile_devices",
    )
    total_counts = models.IntegerField(default=0)
    total_assigns = models.IntegerField(default=0)

    class Meta:
        db_table = "mobile_devices"
        ordering = ["-last_seen_at"]

    def __str__(self):
        return f"{self.device_uuid[:8]}… ({self.last_user_id or 'no-user'})"


class LoginEvent(models.Model):
    """
    One row per login attempt (success or failure) against the web/mobile API.
    Captures client IP, User-Agent and device hints so admins can audit access.
    """
    user = models.ForeignKey(
        "accounts.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="login_events",
    )
    username_attempted = models.CharField(max_length=150, blank=True, default="")
    success = models.BooleanField(default=False)
    failure_reason = models.CharField(max_length=200, blank=True, default="")
    ip_address = models.CharField(max_length=64, blank=True, default="")
    user_agent = models.CharField(max_length=500, blank=True, default="")
    device_uuid = models.CharField(max_length=64, blank=True, default="")
    platform = models.CharField(max_length=20, blank=True, default="")
    app_version = models.CharField(max_length=30, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "login_events"
        ordering = ["-created_at"]

    def __str__(self):
        status = "OK" if self.success else "FAIL"
        return f"[{status}] {self.username_attempted or '?'} @ {self.created_at:%Y-%m-%d %H:%M}"
