# Generated by Django 4.2.23 on 2026-04-29 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0004_receipt_and_lankaqr_fields'),
        ('pos', '0006_rename_pos_bill_outlet_date_idx_pos_bills_outlet__c71a6c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_str', models.CharField(max_length=8)),
                ('counter', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_sequences', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_bill_sequences',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('endpoint', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_idempotency_keys',
                'indexes': [models.Index(fields=['key'], name='pos_idempot_key_640af8_idx'), models.Index(fields=['created_at'], name='pos_idempot_created_82e9fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('max_line_discount_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('max_bill_discount_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('max_bill_discount_amount', models.DecimalField(decimal_places=2, default=5000, max_digits=14)),
                ('require_manager_pin_above_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_policies', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_discount_policies',
                'ordering': ['outlet_id', 'role'],
                'indexes': [models.Index(fields=['outlet', 'role'], name='pos_discoun_outlet__abcd3a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='discountpolicy',
            constraint=models.UniqueConstraint(fields=('outlet', 'role'), name='uniq_discount_policy_outlet_role'),
        ),
        migrations.AddIndex(
            model_name='billsequence',
            index=models.Index(fields=['outlet', 'date_str'], name='pos_bill_se_outlet__d1211d_idx'),
        ),
        migrations.AddConstraint(
            model_name='billsequence',
            constraint=models.UniqueConstraint(fields=('outlet', 'date_str'), name='uniq_bill_seq_outlet_date'),
        ),
    ]
