# Generated by Django 4.2.23 on 2026-04-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_billsequence_idempotencykey_discountpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='batches_consumed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
