# Generated by Django 4.2.23 on 2026-04-29 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0004_receipt_and_lankaqr_fields'),
        ('pos', '0011_promotions_coupons_giftcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('rate_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('inclusive', models.BooleanField(default=False)),
                ('applies_to_categories', models.JSONField(blank=True, default=list)),
                ('excluded_categories', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_tax_components',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='pos_coupons_outlet__03f52f_idx',
            old_name='pos_coupons_outlet__act_idx',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='pos_coupons_code_88b09e_idx',
            old_name='pos_coupons_code_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='pos_coupon__coupon__6534c1_idx',
            old_name='pos_couponred_coupon_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='pos_coupon__custome_bfea15_idx',
            old_name='pos_couponred_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='giftcard',
            new_name='pos_gift_ca_outlet__9ba8e0_idx',
            old_name='pos_giftcards_outlet_idx',
        ),
        migrations.RenameIndex(
            model_name='giftcard',
            new_name='pos_gift_ca_serial_c83bf8_idx',
            old_name='pos_giftcards_serial_idx',
        ),
        migrations.RenameIndex(
            model_name='giftcardtxn',
            new_name='pos_gift_ca_card_id_dd434a_idx',
            old_name='pos_gctxn_card_idx',
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_exempt_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='couponredemption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='giftcardtxn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='taxcomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_components', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcomponent',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_components', to='outlets.outlet'),
        ),
        migrations.AddIndex(
            model_name='taxcomponent',
            index=models.Index(fields=['outlet', 'is_active'], name='pos_tax_com_outlet__d53496_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcomponent',
            index=models.Index(fields=['code'], name='pos_tax_com_code_a98142_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxcomponent',
            constraint=models.UniqueConstraint(fields=('outlet', 'code'), name='uniq_taxcomp_outlet_code'),
        ),
    ]
