# Generated by Django 4.2.23 on 2026-04-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0004_receipt_and_lankaqr_fields'),
        ('pos', '0012_taxcomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('csv_text', models.TextField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_exports', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_exports', to='outlets.outlet')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_exports', to='pos.shift')),
            ],
            options={
                'db_table': 'pos_gl_exports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GLEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=80)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('entry_date', models.DateField()),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries', to='pos.bill')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pos.glexport')),
            ],
            options={
                'db_table': 'pos_gl_entries',
            },
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('purpose', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('ar_credit', 'AR / Store Credit'), ('sales', 'Sales Revenue'), ('sales_return', 'Sales Return'), ('tax', 'Tax Payable'), ('discount', 'Discount Given'), ('rounding', 'Rounding'), ('tender_other', 'Other Tender'), ('gift_card_liability', 'Gift Card Liability')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_gl_accounts',
                'ordering': ['outlet_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('safe_deposit_ref', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('disputed', 'Disputed')], default='pending', max_length=10)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_handovers_given', to=settings.AUTH_USER_MODEL)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_handovers_collected', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='pos.shift')),
            ],
            options={
                'db_table': 'pos_cash_handovers',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='glexport',
            index=models.Index(fields=['outlet', '-generated_at'], name='pos_gl_expo_outlet__566a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='glentry',
            index=models.Index(fields=['export'], name='pos_gl_entr_export__a17447_idx'),
        ),
        migrations.AddIndex(
            model_name='glentry',
            index=models.Index(fields=['bill'], name='pos_gl_entr_bill_id_25dc28_idx'),
        ),
        migrations.AddIndex(
            model_name='glentry',
            index=models.Index(fields=['account_code', 'entry_date'], name='pos_gl_entr_account_df7aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='glaccount',
            index=models.Index(fields=['outlet', 'purpose', 'is_active'], name='pos_gl_acco_outlet__1094f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='glaccount',
            constraint=models.UniqueConstraint(fields=('outlet', 'code'), name='uniq_glacct_outlet_code'),
        ),
        migrations.AddIndex(
            model_name='cashhandover',
            index=models.Index(fields=['shift'], name='pos_cash_ha_shift_i_577478_idx'),
        ),
        migrations.AddIndex(
            model_name='cashhandover',
            index=models.Index(fields=['collected_by', '-collected_at'], name='pos_cash_ha_collect_95513e_idx'),
        ),
    ]
