# Generated by Django 4.2.23 on 2026-04-29 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_receipt_and_lankaqr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0013_glexport_glentry_glaccount_cashhandover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(blank=True, default='', max_length=200)),
                ('rate_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('basis', models.CharField(choices=[('line_total', 'Line Total'), ('line_profit', 'Line Profit'), ('line_qty', 'Per Unit')], default='line_total', max_length=12)),
                ('priority', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_commission_rules',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billline',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rep_bill_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['sales_rep', 'created_at'], name='pos_bills_sales_r_d35edd_idx'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='outlets.outlet'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['outlet', 'is_active', 'priority'], name='pos_commiss_outlet__726d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['rep'], name='pos_commiss_rep_id_35cb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['item_category'], name='pos_commiss_item_ca_df8841_idx'),
        ),
    ]
