# Generated by Django 4.2.23 on 2026-04-29 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0004_receipt_and_lankaqr_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0015_goodsreceipt_purchaseorder_purchaseorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock (testing)'), ('sampath', 'Sampath VishwaQR'), ('hnb', 'HNB Solo'), ('frimi', 'FriMi'), ('genie', 'Genie'), ('helapay', 'HelaPay')], max_length=12)),
                ('merchant_id', models.CharField(blank=True, default='', max_length=120)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=120)),
                ('callback_url', models.CharField(blank=True, default='', max_length=300)),
                ('sandbox', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_gateways', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_payment_gateways',
                'ordering': ['outlet_id', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock (testing)'), ('dialog', 'Dialog'), ('mobitel', 'Mobitel'), ('hutch', 'Hutch'), ('textit', 'TextIt')], max_length=12)),
                ('sender_id', models.CharField(blank=True, default='', max_length=20)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('endpoint_url', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_configs', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_sms_configs',
                'ordering': ['outlet_id', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='LKR', max_length=8)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=120)),
                ('payment_url', models.TextField(blank=True, default='')),
                ('qr_data', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='pos.bill')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intents', to='pos.paymentgatewayconfig')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payment_intents', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_payment_intents',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=120)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='pos.bill')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='pos.smsconfig')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pos_sms_logs',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['outlet', '-queued_at'], name='pos_sms_log_outlet__932159_idx'), models.Index(fields=['status'], name='pos_sms_log_status_4aab08_idx'), models.Index(fields=['bill'], name='pos_sms_log_bill_id_3525af_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='smsconfig',
            index=models.Index(fields=['outlet', 'is_active'], name='pos_sms_con_outlet__2694bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='smsconfig',
            constraint=models.UniqueConstraint(fields=('outlet', 'provider'), name='uniq_smsconf_outlet_provider'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['outlet', 'status'], name='pos_payment_outlet__118e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider_ref'], name='pos_payment_provide_a5711f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['bill'], name='pos_payment_bill_id_d26606_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgatewayconfig',
            index=models.Index(fields=['outlet', 'is_active'], name='pos_payment_outlet__d74355_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(fields=('outlet', 'provider'), name='uniq_gateway_outlet_provider'),
        ),
    ]
