# Generated by Django 5.0.4 on 2026-04-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=300)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_barcode', 'Pending Barcode')], default='pending_barcode', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barcode_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('barcode_assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_barcodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='PendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=300)),
                ('first_seen_date', models.DateField(auto_now_add=True)),
                ('staff_note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_seen_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='outlets.outlet')),
            ],
            options={
                'db_table': 'pending_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
