# Generated by Django 5.0.4 on 2026-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_category_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
