# Generated by Django 5.0.4 on 2026-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_cost_and_reorder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itempricehistory',
            new_name='item_price__item_id_b72244_idx',
            old_name='ph_item_idx',
        ),
        migrations.RenameIndex(
            model_name='itempricehistory',
            new_name='item_price__outlet__32d1b6_idx',
            old_name='ph_outlet_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='stock_movem_outlet__2d77d0_idx',
            old_name='stmov_outlet_item_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='stock_movem_kind_671465_idx',
            old_name='stmov_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='stock_movem_ref_typ_d4fc82_idx',
            old_name='stmov_ref_idx',
        ),
    ]
