# Generated by Django 4.2.23 on 2026-04-29 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0011_ensure_pos_snapshot_unique'),
        ('items', '0017_rename_ph_item_idx_item_price__item_id_b72244_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grn_ref', models.CharField(blank=True, default='', max_length=80)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='items.item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_batches', to='uploads.supplier')),
            ],
            options={
                'db_table': 'item_batches',
            },
        ),
        migrations.CreateModel(
            name='BatchMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('kind', models.CharField(max_length=20)),
                ('ref_type', models.CharField(blank=True, default='', max_length=80)),
                ('ref_id', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='items.itembatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['item', 'expiry_date'], name='item_batche_item_id_b8aaad_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['item', 'is_active'], name='item_batche_item_id_bcfa28_idx'),
        ),
        migrations.AddIndex(
            model_name='itembatch',
            index=models.Index(fields=['batch_no'], name='item_batche_batch_n_193407_idx'),
        ),
        migrations.AddConstraint(
            model_name='itembatch',
            constraint=models.UniqueConstraint(fields=('item', 'batch_no'), name='uniq_item_batch_no'),
        ),
        migrations.AddIndex(
            model_name='batchmovement',
            index=models.Index(fields=['batch', '-created_at'], name='batch_movem_batch_i_6c5230_idx'),
        ),
    ]
