# Generated by Django 4.2.23 on 2026-04-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_seed_more_units'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='itempackunit',
            new_name='item_pack_u_item_id_ab7428_idx',
            old_name='item_pack_u_item_id_idx',
        ),
        migrations.RenameIndex(
            model_name='itempackunit',
            new_name='item_pack_u_barcode_faf630_idx',
            old_name='item_pack_u_barcode_idx',
        ),
    ]
