# Generated by Django 4.2.23 on 2026-06-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_rename_item_pack_u_item_id_idx_item_pack_u_item_id_ab7428_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_daily_count',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
